// Generated by CoffeeScript 1.9.1
(function() {
  var Docset;

  Docset = (function() {
    function Docset(path) {
      this.path = path;
    }

    return Docset;

  })();

}).call(this);

//# sourceMappingURL=docset.js.map
