// Generated by CoffeeScript 1.9.1
(function() {
  var DocsetInfo, fs, xml2js;

  fs = require('fs');

  xml2js = require('xml2js');

  DocsetInfo = (function() {
    function DocsetInfo() {}

    DocsetInfo.prototype.fromPlist = function(filePath) {
      var error, infoFileData;
      infoFileData = null;
      try {
        infoFileData = fs.readFileSync(filePath);
      } catch (_error) {
        error = _error;
        console.err(error);
      }
      return xml2js.parseString(infoFileData, function(err, result) {
        return console.log(result);
      });
    };

    return DocsetInfo;

  })();

}).call(this);

//# sourceMappingURL=docsetinfo.js.map
