// Generated by CoffeeScript 1.9.1
(function() {
  var ExtractInfo, Extractor;

  Extractor = (function() {
    function Extractor(parent) {}

    Extractor.prototype.extract = function(filePath, destination, root) {};

    Extractor.prototype.error = function(filePath, message) {};

    Extractor.prototype.completed = function(filePath) {};

    Extractor.prototype.progress = function(filePath, extracted, total) {};

    return Extractor;

  })();

  ExtractInfo = (function() {
    function ExtractInfo() {}

    ExtractInfo.prototype.extractor = null;

    ExtractInfo.prototype.archiveHandle = null;

    ExtractInfo.prototype.filePath = null;

    ExtractInfo.prototype.totalBytes = null;

    ExtractInfo.prototype.extractedBytes = null;

    return ExtractInfo;

  })();

}).call(this);

//# sourceMappingURL=extractor.js.map
